name: Deploy Flutter Web to Vercel

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Ativar suporte web
        run: flutter config --enable-web

      - name: Instalar dependências
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Vincular projeto Vercel (sem prompt)
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Gerar .vercel/output com vercel build
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy para produção com --prebuilt
        run: vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}